services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - foundit-network

networks:
  foundit-network:
    driver: bridge
